# Generated by Django 3.1.3 on 2020-11-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('song', models.FileField(upload_to='songs')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('listen_count', models.IntegerField(blank=True, null=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
