# Generated by Django 3.1.3 on 2020-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='listen_count',
        ),
        migrations.AddField(
            model_name='track',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
