# Generated by Django 3.1.3 on 2020-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_listen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='listen_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
