# Generated by Django 3.1.3 on 2020-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20201125_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='listen_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
